backend/src/main/java/io/f1/backend/BackendApplication.java, backend/src/main/java/io/f1/backend/domain/admin/entity/Admin.java, backend/src/main/java/io/f1/backend/domain/game/ConnectionState.java, backend/src/main/java/io/f1/backend/domain/game/GameSetting.java, backend/src/main/java/io/f1/backend/domain/game/Player.java, backend/src/main/java/io/f1/backend/domain/game/Room.java, backend/src/main/java/io/f1/backend/domain/game/RoomManager.java, backend/src/main/java/io/f1/backend/domain/game/RoomSetting.java, backend/src/main/java/io/f1/backend/domain/game/RoomState.java, backend/src/main/java/io/f1/backend/domain/question/entity/Question.java, backend/src/main/java/io/f1/backend/domain/question/entity/TextQuestion.java, backend/src/main/java/io/f1/backend/domain/quiz/entity/Quiz.java, backend/src/main/java/io/f1/backend/domain/quiz/entity/QuizType.java, backend/src/main/java/io/f1/backend/domain/stat/entity/Stat.java, backend/src/main/java/io/f1/backend/domain/user/entity/User.java, backend/src/main/java/io/f1/backend/global/config/WebConfig.java, backend/src/main/java/io/f1/backend/global/config/WebSocketConfig.java, backend/src/main/java/io/f1/backend/global/entity/BaseEntity.java, backend/src/main/java/io/f1/backend/global/exception/CustomException.java, backend/src/main/java/io/f1/backend/global/security/enums/Role.java, backend/src/test/java/io/f1/backend/BackendApplicationTests.java
- #1 
웹소켓 config 파일 생성 
웹소켓 연결 확인
=> [feat] 웹소켓 config 파일 생성

.github/workflows/release.yml
- #7 
label과 함께 main 브랜치에 push 된 merge commit에 대해 자동으로 release 하도록 하는 GitHub Action workflow 추가
[Bumpr](https://github.com/marketplace/actions/bumpr-bump-version-when-merging-pull-request-with-specific-labels)
[Tested PR](https://github.com/dlsrks1021/kopring_lintertest/pull/2)
=> :sparkles: feat: GitHub Action 자동 Release 추가

.github/workflows/test.yml, backend/build.gradle, backend/src/main/java/io/f1/backend/domain/user/entity/User.java, backend/src/test/resources/application.yml
- #9 
- dev 브랜치로의 PR이 발생할 경우 Spring test를 자동으로 수행하도록 하는 CI를 추가했습니다.
- test 패키지의 application.yml 설정 파일을 추가해 h2 in-memory db를 통해 테스트를 수행하도록 추가했습니다.
- User 클래스에서 Table 어노테이션을 통해 데이터베이스의 user 예약어와 겹치지 않도록 수정했습니다.
=> [feat] GitHub Action 자동 테스트 추가

backend/.gitignore, backend/src/main/java/io/f1/backend/domain/question/app/QuestionService.java, backend/src/main/java/io/f1/backend/domain/question/dao/QuestionRepository.java, backend/src/main/java/io/f1/backend/domain/question/dao/TextQuestionRepository.java, backend/src/main/java/io/f1/backend/domain/question/dto/QuestionRequest.java, backend/src/main/java/io/f1/backend/domain/question/entity/Question.java, backend/src/main/java/io/f1/backend/domain/question/entity/TextQuestion.java, backend/src/main/java/io/f1/backend/domain/question/mapper/QuestionMapper.java, backend/src/main/java/io/f1/backend/domain/question/mapper/TextQuestionMapper.java, backend/src/main/java/io/f1/backend/domain/quiz/api/QuizController.java, backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java, backend/src/main/java/io/f1/backend/domain/quiz/dao/QuizRepository.java, backend/src/main/java/io/f1/backend/domain/quiz/dto/QuizCreateRequest.java, backend/src/main/java/io/f1/backend/domain/quiz/dto/QuizCreateResponse.java, backend/src/main/java/io/f1/backend/domain/quiz/entity/Quiz.java, backend/src/main/java/io/f1/backend/domain/quiz/mapper/QuizMapper.java, backend/src/main/java/io/f1/backend/domain/user/dao/UserRepository.java, backend/src/main/java/io/f1/backend/domain/user/entity/User.java, backend/src/main/java/io/f1/backend/global/config/WebConfig.java, backend/src/main/resources/application.yml, backend/src/main/resources/data.sql, backend/src/test/resources/application.yml
- #4 
퀴즈 생성 API를 생성했습니다. 
- Postman 에서도 정상적으로 생성되는 것을 확인했습니다. 
- 이 부분은 테스트 코드를 지금 짜둬도 이후 시큐리티 구현 이후 변경되는 부분이 많을 것 같아 이후 테스트 코드를 작성하도록 하겠습니다. 
아직 시큐리티가 적용되어있지 않아, User는 하드 코딩해서 넣어주었습니다. 
저희는 db client 콘솔으로 INSERT 문을 실행하는 게 쉽지만, 혹시나 프론트 개발자님이 그 부분이 어려우실까봐 `application.yml`에 
```
spring:
sql:
init:
mode: always # 현재는 data.sql 에서 더미 유저 자동 추가를 위해 넣어뒀음.
jpa:
defer-datasource-initialization: true # 현재는 data.sql 에서 더미 유저 자동 추가를 위해 넣어뒀음.
```
이 부분을 추가해두었습니다. 
`resources/data.sql`에는 Stat이 비워져있는 `id=1`인 User를 INSERT 해두었습니다. 
- 또, 많은 부분에서 Quiz 생성에 필요한 `User creator` 때문에 TODO 주석이 있습니다. 참고바랍니다.
- 프로젝트의 루트 경로에서 `images/thumbnail/` 에 저장됩니다. 
- `application.yml`에서 퀴즈 썸네일 디폴트 이미지 경로도 설정해두었습니다. 환경에서는 임의의 default.png를 두고 테스트를 진행했습니다.
- 아직 확장성을 고려해서 코드를 작성하진 않았습니다. 
- 퀴즈 생성 이외에 수정, 삭제 등의 API 를 추가 구현하면서 더 고민해보고 …
=> [feat] 퀴즈 생성 기능 추가 

backend/build.gradle, backend/src/main/java/io/f1/backend/domain/stat/entity/Stat.java, backend/src/main/java/io/f1/backend/domain/user/api/SignupController.java, backend/src/main/java/io/f1/backend/domain/user/app/CustomOAuthUserService.java, backend/src/main/java/io/f1/backend/domain/user/app/UserService.java, backend/src/main/java/io/f1/backend/domain/user/app/handler/CustomAuthenticationEntryPoint.java, backend/src/main/java/io/f1/backend/domain/user/app/handler/OAuthLogoutSuccessHandler.java, backend/src/main/java/io/f1/backend/domain/user/app/handler/OAuthSuccessHandler.java, backend/src/main/java/io/f1/backend/domain/user/dao/UserRepository.java, backend/src/main/java/io/f1/backend/domain/user/dto/SessionUser.java, backend/src/main/java/io/f1/backend/domain/user/dto/SignupRequestDto.java, backend/src/main/java/io/f1/backend/domain/user/dto/SignupResponseDto.java, backend/src/main/java/io/f1/backend/domain/user/dto/UserPrincipal.java, backend/src/main/java/io/f1/backend/domain/user/entity/User.java, backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java, backend/src/main/java/io/f1/backend/global/util/SecurityUtils.java, backend/src/main/resources/application.yml
- #2 
- Kakao OAuth 회원가입, 로그인, 로그아웃 기능을 구현했습니다.
- 아직 커스텀 예외처리는 적용하지 않았습니다.
- Kakao OAuth 애플리케이션 정보는 수업 시간에 생성했던 환경을 그대로 사용했습니다. 이 부분도 어떻게 관리할 지 논의가 필요해보입니다.
- 제가 구현한 기능의 흐름은 다음과 같습니다
- 뇌이싱 시작하기 버튼 클릭 → /oauth2/authorization/kakao 으로 요청 → Kakao 로그인 화면에서 ID/Password 입력 후 OAuth 인증 → 닉네임 설정 페이지에서 닉네임 입력 후 /signup 요청 → 회원가입 완료
- 만약 Kakao OAuth 인증만 한 상태로 닉네임 설정을 하지 않으면 User 테이블에 nickname이 null인 user가 생성됨 → 그래서 사용자 정보를 불러와서 nickname이 null인 사용자면 닉네임 설정 페이지로 분기 되도록 json 응답 처리
- 이것에 대한 json 응답은 API 명세서에 추가했습니다.
```java
@Override
public void onAuthenticationSuccess(HttpServletRequest request, HttpServletResponse response,
Authentication authentication) throws IOException {
UserPrincipal principal = (UserPrincipal) authentication.getPrincipal(); …
```
=> [feat] Kakao OAuth 회원가입, 로그인, 로그아웃 기능

.github/workflows/bump-version.yml, .github/workflows/release.yml, backend/Dockerfile, backend/src/main/resources/application.yml
- #22 
- Dockerfile 정의
- versioning 작업을 bump-version workflow로 분리
- release workflow에 docker image 빌드 추가
- Redis 관련 설정 주석처리
아래 forked repository에서 시험 완료했습니다.
https://github.com/dlsrks1021/WEB5_7_F1_BE/pull/5
도커 이미지 빌드를 위한 절차는 아래와 같습니다.
1. dev -> main으로의 PR 생성
2. 해당 PR에서 bump:patch, bump:minor, bump:major 중 1개 label 설정
3. PR merge 시 자동 이미지 빌드 -> packages에서 확인 가능
=> [feat] Github Action 자동 도커 이미지 빌드 추가

backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java, backend/src/main/java/io/f1/backend/domain/game/event/RoomCreatedEvent.java, backend/src/main/java/io/f1/backend/domain/game/event/RoomDeletedEvent.java, backend/src/main/java/io/f1/backend/domain/game/event/RoomUpdatedEvent.java, backend/src/main/java/io/f1/backend/domain/game/sse/app/SseService.java, backend/src/main/java/io/f1/backend/domain/game/sse/dto/LobbySseEvent.java, backend/src/main/java/io/f1/backend/domain/game/sse/dto/RoomCreatedPayload.java, backend/src/main/java/io/f1/backend/domain/game/sse/dto/RoomDeletedPayload.java, backend/src/main/java/io/f1/backend/domain/game/sse/dto/RoomUpdatedPayload.java, backend/src/main/java/io/f1/backend/domain/game/sse/dto/SseEventType.java, backend/src/main/java/io/f1/backend/domain/game/sse/listener/RoomCreatedEventListener.java, backend/src/main/java/io/f1/backend/domain/game/sse/listener/RoomDeletedEventListener.java, backend/src/main/java/io/f1/backend/domain/game/sse/listener/RoomUpdatedEventListener.java, backend/src/main/java/io/f1/backend/domain/game/sse/mapper/SseMapper.java, backend/src/main/java/io/f1/backend/domain/game/sse/store/SseEmitterRepository.java, backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java
Closes #18 
```
// 연결종료 객체정리
emitter.onCompletion(() -> emitters.remove(emitter));
emitter.onTimeout(() -> emitters.remove(emitter));
emitter.onError(error -> emitters.remove(emitter));
```
이번 작업내용은 아니지만, emitter 객체 해제의 경우는 주석으로 적기에는 조금 길어서 이 부분에 적어두었습니다.
- **onCompletion 발생** -> 브라우저 종료, 새로고침시 자동으로 서버에서 호출됨 / 로비 페이지 벗어날 시에는 FE에서 close() 호출을 명시적으로 해줘야 서버에서 onCompletion 발생
- **onTimeout 발생**-> 해당 객체에 설정된 timeOut 종료 시, 서버에서 호출됨
- **onError**-> 네트워크 끊김 등 클라이언트 연결 예외 시 서버에서 호출됨
1. Room의 생성, 수정, 삭제 메서드에서는 각 작업이 완료된 후, 해당 작업에 대응하는 이벤트 객체(RoomCreatedEvent, RoomUpdatedEvent, RoomDeletedEvent)를 발행합니다.
2. 이 이벤트들은 SseMapper를 통해 LobbySseEvent로 변환되며, 이 과정에서 이벤트 타입(CREATE, UPDATE, DELETE)이 지정되고, 클라이언트에게 전달할 payload가 구성됩니다.
3. 변환된 LobbySseEvent는 이벤트 리스너를 통해 SSE(로비에 있는 사용자)를 구독 중인 모든 클라이언트에게 브로드캐스팅됩니다.
- …
=> [feat] SSE 알림 기능 구현

backend/src/main/java/io/f1/backend/domain/game/dto/request/RoomCreateRequest.java, backend/src/main/java/io/f1/backend/global/exception/CustomException.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/AuthErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/CommonErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/ErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/QuestionErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/QuizErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/UserErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/handler/GlobalExceptionHandler.java, backend/src/main/java/io/f1/backend/global/exception/response/ErrorResponse.java
Closes #35 
에러코드는 공통 에러처리와 도메인별로 Enum클래스를 나누어 놓았습니다. 에러코드가 많지 않은 경우, 하나에 몰아넣고 주석으로 구분하는 경우가 많은데, 분리하는 경우가 각 도메인별 책임분리도 되고,
```
Room room =
roomRepository
.findRoom(request.roomId())
.orElseThrow(() -> new CustomException(RoomErrorCode.ROOM_NOT_FOUND));
```
위 코드와 같이 유지보수나 가독성에 도움이 된다고 판단하였습니다.
- **handleCustomException**
→ CustomException 을 잡아서, 예외에 담긴 커스텀 에러코드와 메시지, HTTP 상태코드를 사용해 응답을 만들어서 내려줍니다.
즉, 직접 정의한 비즈니스 예외 처리용입니다.
- **handleException**
→ Exception 클래스(모든 예외의 최상위)를 잡아서, 정의하지 않은 모든 예외에 대해 500 서버 에러 응답을 내려줍니다.
즉, 의도하지 않은 에러, 예상하지 못한 에러를 위한 보험입니다.
- **handleMethodArgumentNotValidException**
→ @Valid 검증 실패 시 발생하는 MethodArgumentNotValidException 을 잡아, 필드별 에러 메시지 중 첫 번째를 뽑아 BAD_REQUEST 코드와 함께 반환합니다.
=> [feat] 커스텀 예외 공통 처리

backend/src/main/java/io/f1/backend/domain/question/api/QuestionController.java, backend/src/main/java/io/f1/backend/domain/question/app/QuestionService.java, backend/src/main/java/io/f1/backend/domain/question/dto/QuestionRequest.java, backend/src/main/java/io/f1/backend/domain/question/dto/QuestionUpdateRequest.java, backend/src/main/java/io/f1/backend/domain/question/entity/Question.java, backend/src/main/java/io/f1/backend/domain/question/entity/TextQuestion.java, backend/src/main/java/io/f1/backend/domain/quiz/api/QuizController.java, backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java, backend/src/main/java/io/f1/backend/domain/quiz/dto/QuizCreateRequest.java, backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java, backend/src/main/java/io/f1/backend/global/validation/TrimmedSize.java, backend/src/main/java/io/f1/backend/global/validation/TrimmedSizeValidator.java
- #43 
문제 수정, 삭제 API를 구현했습니다. 포스트맨으로 정상 동작하는 것 확인했습니다. 
```json
{
"content": "새 문제",
"answer": null 
}
```
- 위와 같이 변경되지 않은 값은 null로 오고, 변경된 값이면 변경된 값을 담아서 요청으로 들어옵니다. 
- 기존 API 명세서에서 `question` -> `content`로 변경했습니다.
수정할 때 빈 문자열을 보내올 수도 있겠다 싶어 퀴즈 제목, 설명 / 퀴즈 문제, 정답도 글자 수에 제한을 둬야겠다고 생각했습니다. 
`QuizCreateRequest` 와 `QuestionCreateRequest`에서 `@NotBlank`와 `@Size`로 유효성 검사를 진행합니다. 
근데, 이랬을 경우 수정 때는 변경되지 않은 값은 `null`로 들어올 수 있기 때문에 `DTO`차원에서 유효성 검사를 해줄 순 없어 서비스에서 글자 수를 검사합니다. 
- 근데 또..!  서비스에서 글자수만 검사할 경우, `"     "` 이러한 문자열이 들어올 수 있다고 생각했습니다. 
- `@NotBlank` 검사를 해줄 수 없기 때문에 서비스에서 `trim()`을 해줘야 하는데 그럼 **글자 수 비교가 생성할 때와 수정할 때 기준이 좀 달라지게 됩니다. (공백 포함 vs 공백 제외)**
그래서 `@TrimmedSize`라는 어노테이션을 추가했고, `ConstraintValidator`를 구현하여 Validator를 정의했습니다. 
이에 따라 퀴즈의 제목, 설명 / 퀴즈의 문제, 정답 글자 수 제한은 다음과 같습니다. 
- 퀴즈 제목 : …
=> [feat] 문제 수정, 삭제 API 구현

backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java, backend/src/main/java/io/f1/backend/global/config/StompChannelInterceptor.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java
- #48 
- 기존에 임시로 넣어놨던 예외를 상황에 맞춰 커스텀 예외로 변환
- 필요한 enum 값 추가 
- 웹소켓 인터셉터 switch -> if 변경
=> [refactor] 커스텀 예외 적용

backend/src/main/java/io/f1/backend/domain/game/app/GameService.java, backend/src/main/java/io/f1/backend/domain/question/app/QuestionService.java, backend/src/main/java/io/f1/backend/domain/quiz/api/QuizController.java, backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java, backend/src/main/java/io/f1/backend/domain/quiz/entity/Quiz.java, backend/src/main/java/io/f1/backend/domain/quiz/mapper/QuizMapper.java, backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/GameErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/QuestionErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/QuizErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java, backend/src/main/resources/application.yml
- #53 
추가로 필요한 에러 코드가 있어서 노션에도 추가해뒀습니다 !
`GameService`, `QuizService`, `QuestionService`에 한해서 커스텀 예외로 변경해두었습니다. 
- 기존 user가 삭제 될 경우 -> null
- `quiz.getCreator().getId()`, `quiz.getCreator().getNickname()` 을 수정했습니다.
- 따로 메서드를 빼서, user가 null이 아닐 시에는 getter를 사용하고, null일 경우, Id와 Nickname에 null을 반환합니다.
- 지난번 StringUtils로 바꾸고 not 조건을 빼먹어서 페이징이 안되던 거였습니다 하핫.
- 이 부분 수정했습니다 !
=> [refactor] Mapper에서 NPE 요소 제거하기 + 커스텀 예외 적용하기

backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java, backend/src/main/java/io/f1/backend/domain/game/dto/PlayerReadyData.java, backend/src/main/java/io/f1/backend/domain/game/store/RoomRepository.java, backend/src/main/java/io/f1/backend/domain/game/store/RoomRepositoryImpl.java, backend/src/main/java/io/f1/backend/domain/game/websocket/GameSocketController.java, backend/src/main/java/io/f1/backend/domain/user/api/SignupController.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java
Closes #50 
- 플레이어의 레디 상태 변경 기능을 추가했습니다.
- `/room/ready/{roomId}`으로 메시지를 SEND할 때마다 사용자의 isReady상태가 토글되고, 해당 방의 구독자들에게 브로드캐스팅 됩니다.
=> [feat] 플레이어 준비 상태 변경 기능

backend/src/main/java/io/f1/backend/global/config/CorsConfig.java, backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java, backend/src/main/java/io/f1/backend/global/util/SecurityUtils.java, backend/src/main/resources/application.yml
- #70 
- 요청 시 쿠키에 JSESSIONID가 세팅이 안되는 문제 발생하여 프론트엔드 도메인 명시적으로 설정했습니다.
- quiz, question API에 대한 요청 권한을 설정 설정했습니다.
- 프론트엔드, 백엔드 배포 환경에 https가 적용이 되고, 서버에서도 same-site: None, secure: true 설정이 되면 로컬 테스트 환경인 http://localhost:3000에서 요청을 보내도 쿠키 전송이 무시된다고 합니다. 그래서 CORS 설정에서 해당 origin은 제거했습니다.
=> [fix] CORS 경로 설정, HTTPS 환경설정

.github/workflows/slack-notify-pr-open.yml
- #80 
- PR Open 시 Slack에 알림을 주는 Github Action을 추가합니다.
[action-slack-notify](https://github.com/rtCamp/action-slack-notify?tab=readme-ov-file)
=> feat: PR Open 시 Slack 알림 Github Action 추가

backend/src/main/java/io/f1/backend/domain/question/app/QuestionService.java, backend/src/main/java/io/f1/backend/domain/quiz/app/QuizService.java, backend/src/main/java/io/f1/backend/domain/quiz/mapper/QuizMapper.java, backend/src/main/java/io/f1/backend/global/util/SecurityUtils.java
- #36 
- 다만, `data.sql`은 이후 FE 개발자님도 퀴즈 생성 때문에 사용하시는 것 같아서 지우지 않았습니다.
- User 정보는 `SecurityUtils.getCurrentUserId`를 통해 받아오도록 수정했습니다.
- 관리자일 때 : 퀴즈 수정, 삭제 가능 / 문제 수정, 삭제 가능
- 사용자일 때 : 퀴즈의 creator가 현재 로그인한 유저와 같은지 비교 후 -> 같다면 수정, 삭제 가능
=> [feat] 관리자 퀴즈 수정, 삭제 로직 추가 + User 하드코딩 삭제

backend/src/main/java/io/f1/backend/domain/game/app/GameService.java, backend/src/main/java/io/f1/backend/domain/game/dto/request/GameStartRequest.java, backend/src/main/java/io/f1/backend/domain/game/websocket/GameSocketController.java, backend/src/main/java/io/f1/backend/domain/game/websocket/WebSocketUtils.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/GameErrorCode.java, backend/src/main/java/io/f1/backend/global/exception/errorcode/RoomErrorCode.java
Closes #74 
- 게임 시작의 요청 메시지를 제거했습니다. `type`과 `message`모두 없습니다.
- 게임 시작에 문제가 될 수 있는 부분들을 추가하고 예외처리하였습니다. 아래는 추가된 예외입니다.
1. 방장이 아닌 사람이 게임을 시작하는 경우 [**ErrorCode** : E403005, message: "방장만 게임 시작이 가능합니다."]
2.  이미 게임 진행 중에 또 게임 시작을 하는 경우 [**ErrorCode** : E400015, message: "이미 게임이 진행 중 입니다."]
- gameStart의 예외처리가 많아져서 메서드로 분리했습니다.
- GameSocketController에 존재하던 getSessionId()와 getSessionUser를 유틸클래스로 옮겨놓았습니다.
- 저만 바보여서 몰랐을 수 도 있지만... 웹소켓은 HTTP요청 기반의 통신이 아니므로, @AuthenticationPrincipal로 UserPrincipal을 @MessageMapping의 인자로 직접 주입받는 것이 불가능합니다.
- Spring Security는 인증 정보를 SecurityContextHolder의 ThreadLocal에 저장하는 방식인데, WebSocket 메시지 처리는 다른 쓰레드에서 이루어지기 때문에 기존의 인증 정보가 공유되지 않습니다.
- 
-  그래서, 매번 SEND마다 컨텍스트홀더에 인증 정보를 수동으로 계속 주입해줘야 하는... 마치 밥을 한 숟가락 먹을때마다, 밥을 새로 짓는듯한.... 아주 비효율의 끝판왕을 제가 하고 있었습니다. 그래서 기존 방식대로 …
=> [refactor] 게임 시작 요청 리팩토링

backend/src/main/java/io/f1/backend/domain/stat/api/StatController.java, backend/src/main/java/io/f1/backend/domain/stat/app/StatService.java, backend/src/main/java/io/f1/backend/domain/stat/dao/StatRepository.java, backend/src/test/java/io/f1/backend/domain/stat/StatBrowserTest.java
- #89 
- service 계층에 transactional을 빼먹다니
- 닉네임을 통해 랭킹을 조회
1. nickname을 통해 score를 확인합니다.
2. score의 페이지 위치를 확인 및 pageable을 생성합니다.
3. pageable을 통해 페이지를 조회해 결과를 반환합니다.
native query를 사용하면 1-2번 과정의 통합이 가능하지만, 아래와 같은 이유로 native query를 사용하지 않았습니다.
- 테스트 코드에서는 user 테이블이 user_test 테이블로 이름이 변경되기 때문에 native query 사용 시 user 테이블 참조가 불가능합니다.
- MySQL에 종속된 쿼리 사용 시 Redis로의 전환에서 다시 수정이 필요할 수 있습니다.
위 일련의 과정에 대해서는 Redis 리팩토링 시에 효율적인 방법을 찾아보도록 하겠습니다.
=> [feat] 유저 닉네임을 통해 랭킹 조회

backend/src/main/java/io/f1/backend/domain/admin/api/AdminController.java, backend/src/main/java/io/f1/backend/domain/admin/app/AdminService.java, backend/src/main/java/io/f1/backend/domain/user/app/UserService.java, backend/src/main/java/io/f1/backend/domain/user/dao/UserRepository.java, backend/src/test/java/io/f1/backend/domain/admin/app/AdminServiceTests.java, backend/src/test/resources/datasets/admin/search-user.yml
- #99 
- 관리자 유저 목록 조회 화면에서 유저 정보 검색 시 사용될 기능을 구현했습니다
- /admin/users 에 해당하는 API 명세서를 수정했습니다.
=> [feat] 유저 닉네임으로 정보 조회

backend/build.gradle, backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java, backend/src/main/resources/application.yml
- #113 
운영 환경에 프로메테우스 적용을 위해 아래의 사항들을 적용했습니다.
- 설정 파일에 prod 프로필 추가
- Spring Actuator 활성화
- Spring in-memory userDetailService에 프로메테우스 계정 설정
- PROMETHEUS Role을 추가해 actuator path에 대한 접근 허용
=> [feat] 프로메테우스 적용

backend/src/main/java/io/f1/backend/domain/game/app/GameService.java, backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java, backend/src/main/java/io/f1/backend/domain/game/model/Room.java, backend/src/test/java/io/f1/backend/domain/game/app/RoomServiceTests.java
- #124 
- 제가 모든 플레이어의 레디 상태를 원상복구 시켜놔서 발생했던 이슈입니다. 
-  `resetAllPlayerReadyStates();` 메서드를 이용해서 방장을 제외한 플레이어의 레디 상태만 바꾸도록 변경했습니다.
- 연결이 끊긴 플레이어가 있을 때만 PLAYER_LIST가 브로드캐스팅되도록 되어있었습니다.
- disconnectedPlayers 리스트가 비었을 때만 해당 로직을 타고, 아닐 때는 PLAYER_LIST를 바로 브로드캐스팅해주도록 분기 처리했습니다.
- 연결이 끊긴 플레이어가 있을 때, SYSTEM_NOTICE, PLAYER_LIST를 여러 번 브로드캐스팅하게끔 구현되어있었습니다.
- SYSTEM_NOTICE는 개별 플레이어가 나갈 때마다 브로드캐스팅해주는 게 맞지만, PLAYER_LIST는 한 번만 응답으로 내려가도 되기 때문에, 반복문 밖으로 뺐습니다.
=> [fix] 게임 종료 시 PLAYER_LIST 메세지 누락, 방장 레디 풀림 이슈 해결

backend/src/main/java/io/f1/backend/domain/game/app/GameService.java, backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java, backend/src/main/java/io/f1/backend/domain/game/dto/request/GameSettingChanger.java, backend/src/main/java/io/f1/backend/domain/game/dto/request/QuizChangeRequest.java, backend/src/main/java/io/f1/backend/domain/game/dto/request/RoundChangeRequest.java, backend/src/main/java/io/f1/backend/domain/game/dto/request/TimeLimitChangeRequest.java, backend/src/main/java/io/f1/backend/domain/game/mapper/RoomMapper.java, backend/src/main/java/io/f1/backend/domain/game/sse/mapper/SseMapper.java
Closes #126 
- SSE 방 삭제 이벤트 퍼블리싱
- 유저 수 조회 메서드 변경
- 퀴즈 변경 시에만 SSE 업데이트 날아가도록 수정
=> [refactor] SSE 방 삭제 이벤트 퍼블리싱, 유저 수 조회 메서드 변경

backend/src/main/java/io/f1/backend/global/config/CorsConfig.java, backend/src/main/resources/application.yml
- #132 
현재는 동일한 backend 컨테이너에서 운영/개발 환경이 혼재한 상태입니다.
이에 대해 docker compose를 운영과 개발에 맞춰 분리 작업을 진행하고자 아래와 같은 작업을 진행했습니다.
- 개발 환경에 대한 프로필을 추가하고 프로메테우스를 통한 모니터링이 가능하도록 설정을 추가했습니다.
- 추후 Flyway 도입 시 운영 환경에서 적용이 필요한 설정들을 TODO와 함께 주석 추가해 두었습니다.
- `api-brainrace.duckdns.org` cors 설정을 추가했습니다.
- dev 환경에 대해서 기존 포트를 통한 분리에서 도메인을 통한 환경 분리 작업을 진행하고자 추가했습니다.
=> [docs] 운영 / 개발 환경 분리

backend/src/main/java/io/f1/backend/global/config/SecurityConfig.java, backend/src/main/resources/application.yml
- #153 
프로메테우스 관련한 Basic Auth 설정을 해제했습니다.
=> [refactor] 프로메테우스 관련 Basic Auth 설정 해제

backend/src/main/java/io/f1/backend/domain/game/app/GameService.java, backend/src/main/java/io/f1/backend/domain/game/sse/app/SseService.java, backend/src/main/java/io/f1/backend/domain/game/sse/store/SseEmitterRepository.java
Closes #144 
- nginx의 proxy_connect_timeout의 디폴트가 60초로 되어있어, 기본 하트비트의 시간을 30초로 설정해놓았습니다. _Ref(1)_
위 사진 처럼, SSE가 타임아웃이 되기전까지 30초 마다 하트비트를 보내게됩니다.
- 기존 waitTime이 다른 메서드의 락대기에 적용이 된다고 PR을 잘못올린것 같습니다. 어노테이션의 waitTime은 어노테이션이 적용되는 메서드에 한해 락 대기시간이 적용됩니다!😭🙈
(1) https://13months.tistory.com/651
=> [feat] SSE 하트비트 추가

backend/src/main/java/io/f1/backend/domain/game/app/ChatService.java, backend/src/main/java/io/f1/backend/domain/game/app/GameService.java, backend/src/main/java/io/f1/backend/domain/game/model/Room.java, backend/src/test/java/io/f1/backend/domain/game/app/ChatServiceTests.java, backend/src/test/java/io/f1/backend/domain/game/app/GameFlowTests.java
- #134 
1. `AtomicBoolean answered` 를 Room 에 추가했습니다.
- 채팅으로 정답을 맞혔을 때, `false` -> `true`로 바꿔줍니다. 
- 만약, 찰나에 timeout이 실행됐을 때는, 이미 `answered`가 true일 때는, 로직을 실행하지 않도록 return 됩니다.
- 채팅 정답 인정 로직에서는, 타이머를 취소한 후, 다시 `true` -> `false`로 값을 복구해줍니다.
=> [feat] 채팅 정답 처리 동시성 제어

backend/src/main/java/io/f1/backend/BackendApplication.java, backend/src/main/java/io/f1/backend/domain/game/app/RoomService.java, backend/src/main/java/io/f1/backend/domain/game/dto/MessageType.java, backend/src/main/java/io/f1/backend/domain/game/dto/response/HeartbeatResponse.java, backend/src/main/java/io/f1/backend/domain/game/websocket/HeartbeatMonitor.java, backend/src/main/java/io/f1/backend/domain/game/websocket/MessageSender.java, backend/src/main/java/io/f1/backend/domain/game/websocket/WebSocketUtils.java, backend/src/main/java/io/f1/backend/domain/game/websocket/controller/GameSocketController.java, backend/src/main/java/io/f1/backend/domain/game/websocket/controller/HeartbeatController.java, backend/src/main/java/io/f1/backend/domain/game/websocket/eventlistener/WebsocketEventListener.java, backend/src/main/java/io/f1/backend/global/config/WebSocketConfig.java
- #118 
- 클라이언트에서 3번이상 응답이 안올 경우 유저 퇴장처리를 하기위해 `stomp`의 기본 하트비트를 설정하지않고 send 요청으로 하트비트를 구현(`ping-pong`)
- 15초 간격으로 `ping` 을 보내면서 카운트를 1 증가시키고,  `pong` 응답이 오면 카운트를 0으로 초기화.
- 이때 `ping` 을 보내는건 스케줄러로 구현하였고 연결된 세션이 있을때만 동작 
- 테스트는 임시로 FE코드를 수정하였음. 
15초 간격으로 `ping`보내고 `pong` 받기
- FE에서도 마찬가지로 ping 응답이 일정 간격을 두고 3번이상 오지 않으면 `deactivate()`하는 로직 구현 필요
=> [feat] 하트비트 구현 

backend/src/main/java/io/f1/backend/domain/stat/dao/StatRedisRepository.java, backend/src/main/java/io/f1/backend/domain/stat/dao/StatRepositoryAdapter.java
- #173 
- 마이페이지 조회 시 DTO 값의 순서를 잘못되어 수정했습니다.
=> [fix] 마이페이지 DTO 값 순서 변경
